/**
 * Los 66 libros en orden canonico: codigo USFM (el del contrato), nombre en
 * espanol y testamento. La posicion es el indice + 1. `vpl` es el codigo que usa
 * el archivo VPL de eBible.org cuando no coincide con USFM.
 */
export const BIBLE_BOOKS: readonly {
  id: string;
  name: string;
  testament: 'old' | 'new';
  vpl?: string;
}[] = [
  { id: 'GEN', name: 'Génesis', testament: 'old' },
  { id: 'EXO', name: 'Éxodo', testament: 'old' },
  { id: 'LEV', name: 'Levítico', testament: 'old' },
  { id: 'NUM', name: 'Números', testament: 'old' },
  { id: 'DEU', name: 'Deuteronomio', testament: 'old' },
  { id: 'JOS', name: 'Josué', testament: 'old' },
  { id: 'JDG', name: 'Jueces', testament: 'old' },
  { id: 'RUT', name: 'Rut', testament: 'old' },
  { id: '1SA', name: '1 Samuel', testament: 'old' },
  { id: '2SA', name: '2 Samuel', testament: 'old' },
  { id: '1KI', name: '1 Reyes', testament: 'old' },
  { id: '2KI', name: '2 Reyes', testament: 'old' },
  { id: '1CH', name: '1 Crónicas', testament: 'old' },
  { id: '2CH', name: '2 Crónicas', testament: 'old' },
  { id: 'EZR', name: 'Esdras', testament: 'old' },
  { id: 'NEH', name: 'Nehemías', testament: 'old' },
  { id: 'EST', name: 'Ester', testament: 'old' },
  { id: 'JOB', name: 'Job', testament: 'old' },
  { id: 'PSA', name: 'Salmos', testament: 'old' },
  { id: 'PRO', name: 'Proverbios', testament: 'old' },
  { id: 'ECC', name: 'Eclesiastés', testament: 'old' },
  { id: 'SNG', name: 'Cantares', testament: 'old', vpl: 'SOL' },
  { id: 'ISA', name: 'Isaías', testament: 'old' },
  { id: 'JER', name: 'Jeremías', testament: 'old' },
  { id: 'LAM', name: 'Lamentaciones', testament: 'old' },
  { id: 'EZK', name: 'Ezequiel', testament: 'old', vpl: 'EZE' },
  { id: 'DAN', name: 'Daniel', testament: 'old' },
  { id: 'HOS', name: 'Oseas', testament: 'old' },
  { id: 'JOL', name: 'Joel', testament: 'old', vpl: 'JOE' },
  { id: 'AMO', name: 'Amós', testament: 'old' },
  { id: 'OBA', name: 'Abdías', testament: 'old' },
  { id: 'JON', name: 'Jonás', testament: 'old' },
  { id: 'MIC', name: 'Miqueas', testament: 'old' },
  { id: 'NAM', name: 'Nahúm', testament: 'old', vpl: 'NAH' },
  { id: 'HAB', name: 'Habacuc', testament: 'old' },
  { id: 'ZEP', name: 'Sofonías', testament: 'old' },
  { id: 'HAG', name: 'Hageo', testament: 'old' },
  { id: 'ZEC', name: 'Zacarías', testament: 'old' },
  { id: 'MAL', name: 'Malaquías', testament: 'old' },
  { id: 'MAT', name: 'Mateo', testament: 'new' },
  { id: 'MRK', name: 'Marcos', testament: 'new', vpl: 'MAR' },
  { id: 'LUK', name: 'Lucas', testament: 'new' },
  { id: 'JHN', name: 'Juan', testament: 'new', vpl: 'JOH' },
  { id: 'ACT', name: 'Hechos', testament: 'new' },
  { id: 'ROM', name: 'Romanos', testament: 'new' },
  { id: '1CO', name: '1 Corintios', testament: 'new' },
  { id: '2CO', name: '2 Corintios', testament: 'new' },
  { id: 'GAL', name: 'Gálatas', testament: 'new' },
  { id: 'EPH', name: 'Efesios', testament: 'new' },
  { id: 'PHP', name: 'Filipenses', testament: 'new', vpl: 'PHI' },
  { id: 'COL', name: 'Colosenses', testament: 'new' },
  { id: '1TH', name: '1 Tesalonicenses', testament: 'new' },
  { id: '2TH', name: '2 Tesalonicenses', testament: 'new' },
  { id: '1TI', name: '1 Timoteo', testament: 'new' },
  { id: '2TI', name: '2 Timoteo', testament: 'new' },
  { id: 'TIT', name: 'Tito', testament: 'new' },
  { id: 'PHM', name: 'Filemón', testament: 'new' },
  { id: 'HEB', name: 'Hebreos', testament: 'new' },
  { id: 'JAS', name: 'Santiago', testament: 'new', vpl: 'JAM' },
  { id: '1PE', name: '1 Pedro', testament: 'new' },
  { id: '2PE', name: '2 Pedro', testament: 'new' },
  { id: '1JN', name: '1 Juan', testament: 'new', vpl: '1JO' },
  { id: '2JN', name: '2 Juan', testament: 'new', vpl: '2JO' },
  { id: '3JN', name: '3 Juan', testament: 'new', vpl: '3JO' },
  { id: 'JUD', name: 'Judas', testament: 'new' },
  { id: 'REV', name: 'Apocalipsis', testament: 'new' },
];
